### ISSUE TITLE
Crashes Lunar upon launching

### ISSUE THREAD

**Issue by RealSoy** [CecerMCProjects/NoChangeTheGame#6]
Lunar support would be very nice 😊

**Comment by Cecer** [comment]
Could you potentially provide the crash log please as I do not user Lunar.

I can't make any promises on any fixes regarding this but I'm happy to at least take a look into it.

**Comment by RealSoy** [comment]
[crash-2024-05-31_00.54.37-client.txt](https://github.com/user-attachments/files/15509580/crash-2024-05-31_00.54.37-client.txt)

**Comment by Cecer** [comment]
From looking at that crash log it looks like you clicked a button before NoChangeTheGame was even started. There shouldn't even be any buttons to click at that point. The crash log shows that the game had been open for quite a while. 

For some reason, the entry point is either not being called or things are happening in a non-standard order. I could certainly add some checks in to prevent it crashing but it'd still be broken. It's literally not starting the mod.

Honestly, I wouldn't expect this to be resolved by me. This isn't the first time I've seen Lunar doing weird non-standard things.

If you find more information on this, please do let me know. The full client log could potentially help understand what is going on but I don't think it'll really help much if the mod isn't even being started.

**Comment by RealSoy** [comment]
Not sure how much this helps, but in the crash log I sent I crashed after opening the mod menu list and then closing the menu

When I opened the mod menu, I clicked on the NoChangeTheGame mod to try and open the config settings and got this error when hovering my cursor over the settings button
![image](https://github.com/CecerMCProjects/NoChangeTheGame/assets/72706511/75a1aac5-be82-4fe9-a64b-34edca4d4bd0)

**Comment by Cecer** [comment]
Welp. The very first non-mixin thing it does is register the config...
```
    override fun onInitializeClient() {
        val configHolder = AutoConfig.register(NCTGUserConfig::class.java, ::Toml4jConfigSerializer)
        // ...
    }
```

Are there any other exceptions in the main log file or anything? I wonder if something is going badly before the mod properly starts.

**Comment by RealSoy** [comment]
Here's another exception involving the mod. All the other ones involve the userConfig not being initialized

```
Found Entrypoint(client) com.cecer1.projects.mc.nochangethegame.NoChangeTheGameMod
[2024-05-31 01:49:11.829] [info]  [01:49:11] [IchorPipeline/Render thread/INFO] Entrypoint(client) failed to load com.cecer1.projects.mc.nochangethegame.NoChangeTheGameMod in Genesis
[2024-05-31 01:49:11.830] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: java.lang.IllegalStateException: Failed to launch entrypoint com.cecer1.projects.mc.nochangethegame.NoChangeTheGameMod
[2024-05-31 01:49:11.831] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IROHCHIIOOCCRCOCRICCHHRIO.IROHCHIIOOCCRCOCRICCHHRIO.ROOIRICOHCHOCRHHRHRCROHRC(Unknown Source)
[2024-05-31 01:49:11.831] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.ROIORRIRRRIOHOOCCRCIHHHII.ROOIRICOHCHOCRHHRHRCROHRC(Unknown Source)
[2024-05-31 01:49:11.832] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.mdf075d6$lambda$ichor$fabric$clientInitializer$0$a(SourceFile:4928)
[2024-05-31 01:49:11.832] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.Optional.ifPresentOrElse(Unknown Source)
[2024-05-31 01:49:11.833] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.handler$zjm000$ichor$fabric$clientInitializer(SourceFile:4926)
[2024-05-31 01:49:11.833] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.Minecraft.<init>(SourceFile:448)
[2024-05-31 01:49:11.834] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.redirect$zbe000$impl$main$minecraft(SourceFile:656)
[2024-05-31 01:49:11.834] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at Genesis//net.minecraft.client.main.Main.main(SourceFile:223)
[2024-05-31 01:49:11.835] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[2024-05-31 01:49:11.835] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2024-05-31 01:49:11.835] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.ClientGameBootstrap.apply(Unknown Source)
[2024-05-31 01:49:11.836] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[2024-05-31 01:49:11.836] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2024-05-31 01:49:11.837] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.IROHCHIIOOCCRCOCRICCHHRIO.ROOIRICOHCHOCRHHRHRCROHRC(Unknown Source)
[2024-05-31 01:49:11.837] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.run(Unknown Source)
[2024-05-31 01:49:11.837] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
[2024-05-31 01:49:11.838] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Failed to instantiate external Entrypoint(client): com.cecer1.projects.mc.nochangethegame.NoChangeTheGameMod
[2024-05-31 01:49:11.838] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IROHCHIIOOCCRCOCRICCHHRIO.IROHCHIIOOCCRCOCRICCHHRIO.ROOIRICOHCHOCRHHRHRCROHRC(Unknown Source)
[2024-05-31 01:49:11.839] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
[2024-05-31 01:49:11.839] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IROHCHIIOOCCRCOCRICCHHRIO.IROHCHIIOOCCRCOCRICCHHRIO.ROOIRICOHCHOCRHHRHRCROHRC(Unknown Source)
[2024-05-31 01:49:11.839] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	... 15 more
[2024-05-31 01:49:11.840] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoSuchMethodException: com.cecer1.projects.mc.nochangethegame.NoChangeTheGameMod.<init>()
[2024-05-31 01:49:11.840] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor0(Unknown Source)
[2024-05-31 01:49:11.840] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.getConstructor(Unknown Source)
[2024-05-31 01:49:11.841] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	at com.moonsworth.lunar.ichor.IROHCHIIOOCCRCOCRICCHHRIO.IROHCHIIOOCCRCOCRICCHHRIO.ROOIRICOHCHOCRHHRHRCROHRC(Unknown Source)
[2024-05-31 01:49:11.841] [info]  [01:49:11] [Render thread/INFO]: [STDERR]: 	... 17 more
[2024-05-31 01:49:11.841] [info]  [01:49:11] [IchorPipeline/Render thread/INFO] Entrypoint(client) had 11 invokes.
```

**Comment by Cecer** [comment]
That actually explains a lot. Lunar is either not properly handling the Kotlin language adapter... if not just flat out ignoring it.

While I could probably workaround this, I personally feel it's a little out of scope. I'd be more willing to invest some time into solving this if I didn't have to deal with Lunar's ridiculous obfuscation. After having to deal with it once before, I do not want to deal with it again.

**Comment by Cecer** [comment]
As I don't see proper a way for me to resolve this without changing the language, I'm going to close this issue. I really wish Lunar wasn't such a black box... or at least had a public issue tracker.
